### ISSUE TITLE
convert.R error !is.nan(skw) && skw > 1.5 && all(x >= 0, na.rm = TRUE)

### ISSUE THREAD

**Issue by hathawayj** [delta-rho/trelliscope#155]
I get an error as pasted below when I run a trelliscope with facet_trelliscope.  The same plot works with facet_wrap.  I wish I had something more useful to show.  I might be able to provide a clearer example if it is useful.  What are skw and x in the check below?

  facet_trelliscope(~Building_Code+Days)
  facet_wrap(~Building_Code+Days)

Error in if (!is.nan(skw) && skw > 1.5 && all(x >= 0, na.rm = TRUE)) { : 
  missing value where TRUE/FALSE needed

**Comment by hafen** [comment]
I believe this is meant for the trelliscopejs repo? Can you post it there?

**Comment by hathawayj** [comment]
you are correct.
